# Generated by Django 4.1.5 on 2023-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
